language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - travis_retry composer self-update
  
install:
  - composer require "orchestra/testbench=~3.5" --dev --no-update
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.composer/cache
