language: php
os: linux
dist: trusty

jobs:
  include:
    - php: 7.2
      env:
        - LARAVEL_VERSION=^6.0
    - php: 7.4
      env:
        - LARAVEL_VERSION=^6.0
    - php: 8.0
      env:
        - LARAVEL_VERSION=^6.0
    - php: 7.2
      env:
        - LARAVEL_VERSION=^7.0
    - php: 7.4
      env:
        - LARAVEL_VERSION=^7.0
    - php: 8.0
      env:
        - LARAVEL_VERSION=^7.0
    - php: 7.4
      env:
        - LARAVEL_VERSION=^8.0
    - php: 8.0
      env:
        - LARAVEL_VERSION=^8.0
    - php: 8.0
      env:
        - LARAVEL_VERSION=^9.0

before_install:
  - travis_retry composer self-update
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update -n

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.composer/cache
