language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - travis_retry composer self-update
  
install:
  - travis_retry composer install -vvv --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - vendor
