language: php
os: linux
dist: trusty

jobs:
  include:
    - php: 7.1
      env:
        - LARAVEL_VERSION=5.5.*
        - PHPUNIT_VERSION=^7.5
    - php: 7.1
      env:
        - LARAVEL_VERSION=5.6.*
        - PHPUNIT_VERSION=^7.5
    - php: 7.1
      env:
        - LARAVEL_VERSION=5.7.*
        - PHPUNIT_VERSION=^7.5
    - php: 7.1
      env:
        - LARAVEL_VERSION=5.8.*
        - PHPUNIT_VERSION=^7.5
    - php: 7.2
      env:
        - LARAVEL_VERSION=5.5.*
        - PHPUNIT_VERSION=^7.5
    - php: 7.2
      env:
        - LARAVEL_VERSION=5.6.*
        - PHPUNIT_VERSION=^7.5
    - php: 7.2
      env:
        - LARAVEL_VERSION=5.7.*
        - PHPUNIT_VERSION=^7.5
    - php: 7.2
      env:
        - LARAVEL_VERSION=5.8.*
        - PHPUNIT_VERSION=^8.0
    - php: 7.2
      env:
        - LARAVEL_VERSION=^6.0
        - PHPUNIT_VERSION=^8.0
    - php: 7.3
      env:
        - LARAVEL_VERSION=5.5.*
        - PHPUNIT_VERSION=^7.5
    - php: 7.3
      env:
        - LARAVEL_VERSION=5.6.*
        - PHPUNIT_VERSION=^7.5
    - php: 7.3
      env:
        - LARAVEL_VERSION=5.7.*
        - PHPUNIT_VERSION=^7.5
    - php: 7.3
      env:
        - LARAVEL_VERSION=5.8.*
        - PHPUNIT_VERSION=^8.0
    - php: 7.3
      env:
        - LARAVEL_VERSION=^6.0
        - PHPUNIT_VERSION=^8.0
    - php: 7.3
      env:
        - LARAVEL_VERSION=^6.0
        - PHPUNIT_VERSION=^9.0

before_install:
  - travis_retry composer self-update
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update -n
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update -n
  
install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.composer/cache
