name: tests

on: [push]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [8.0, 8.1, 8.2, 8.3, 8.4]
                laravel: [^9.0, ^10.0, ^11.0]
                stability: [prefer-stable]
                exclude:
                    - laravel: ^9.0
                      php: 8.3
                    - laravel: ^9.0
                      php: 8.4
                    - laravel: ^10.0
                      php: 8.0
                    - laravel: ^10.0
                      php: 8.4
                    - laravel: ^11.0
                      php: 8.0
                    - laravel: ^11.0
                      php: 8.1

        name: PHP ${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/files
                  key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
                  restore-keys: |
                        dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-
                        dependencies-laravel-${{ matrix.laravel }}-php-
                        dependencies-laravel-
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, soap, intl, gd, exif, iconv, fileinfo
                  coverage: xdebug2
            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update --dev
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction
            - name: Execute tests
              run: vendor/bin/phpunit --coverage-clover=coverage.xml
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                  files: ./coverage.xml
                  flags: tests
                  name: codecov-umbrella
                  fail_ci_if_error: false
